version: '3.3'
services:
  foos-db:
    build: ./db
    shm_size: 256MB
    container_name: foos-db-cont
    environment:
      - POSTGRES_DB=foos
      - POSTGRES_USER=foos
      - POSTGRES_PASSWORD=foos
    volumes:
      - reskel_data:/var/lib/postgresql/data
  reskel-app:
    build: .
    container_name: reskel-app-cont
    environment:
      - DB_DATABASE=foos
      - DB_USER=foos
      - DB_PASSWORD=foos
      - DB_HOST=foos-db
      - DB_PORT=5432
      - DB_USE_SSL=false
      - DB_POOL_MAX_SIZE=4
      - DB_POOL_MIN_SIZE=1
    ports:
     - 80:3000
    depends_on:
      - foos-db
volumes:
  reskel_data:
